# Generated by Django 3.2 on 2022-08-14 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('belong_war_id', models.IntegerField()),
                ('self_member_id', models.IntegerField()),
                ('self_match_value', models.IntegerField()),
                ('enemy_match_value', models.IntegerField()),
                ('attack_stars', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='League_grade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('belong_league_id', models.IntegerField()),
                ('self_member_id', models.IntegerField()),
                ('attack_stars', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ordinal_id', models.IntegerField()),
                ('belong_league_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.Group')),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.Group')),
                ('leader', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
